version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
    - name: sales    
      identifier: raw_gz_sales
      description: sales of Greenweez
      columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description:  foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: value of order
          - name: quantity
            description: quantity per order  
    - name: product
      identifier: raw_gz_product
      description: products in stock
      columns:
       - name: products_id
         description: products identity
         tests: 
          - unique
          - not_null
       - name: purcHSE_PRICE
         description: price per item

   
    - name: ship
      identifier: raw_gz_ship
      description: shipping of orders
      columns:
       - name: orders_id
         description: orders identity
       - name: ship_fee
         description: cost of shipping  
       - name: shipping_fee_1
         description: ship cost
       - name: logCost
         description: cost of logs
       - name: ship_cost
         description: cost of shipment


   

              
           

        
      

     
    
    
      
    
