version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
            tests:
              - unique:
                 column_name: products_id
              - not_null:
                 column_name: products_id  
          - name: revenue
            description: value of order
          - name: quantity
            description: quantity per order
      - name: product
        identifier: raw_gz_product
        description: products in stock
        columns:
          - name: products_id
            description: products identity
            tests:
              - unique:
                 column_name: products_id
              - not_null:
                 column_name: products_id
          - name: purcHSE_PRICE
            description: price per item

      - name: ship
        identifier: raw_gz_ship
        description: shipping of orders
        columns:
          - name: orders_id
            description: orders identity
          - name: ship_fee
            description: cost of shipping
          - name: shipping_fee_1
            description: ship cost
          - name: logCost
            description: cost of logs
          - name: ship_cost
            description: cost of shipment
models:
  - name: stg_raw__sales
    description: sales of stock
    columns:
      - name: products_id
        description:  product identifier
      - name: stg_raw__product
        description: cleanining rows

  - name: int_orders_margin
    description: order
    columns:
      - name: orders_id
        description: primary key
      - name: date_date
        description: order date
      - name: revenue
        description: total sales
      - name: order_quantity
        description: order quantity
      - name: purchase_cost
        description: cost of all purchases
      - name: margin
        description: cost of goods sold

  - name: int_orders_operational
    description: order
    columns:
      - name: orders_id
        description: primary key
      - name: date_date
        description: order date
      - name: revenue
        description: total sales
      - name: margin
        description: cost of goods solfd
      - name: purchase_cost
        description: cost of all purchases
      - name: shipping_fee
        description: fee of shipping
      - name: logcost
        description: cost per log
      - name: ship_cost
        description: cost per ship
      - name: order_quantity
        description: quantities per order 
      - name: operational margin
        description: operational cost 

  - name: int_sales_margin
    description: order
    columns:
      - name: products_id
        description: product identifier
      - name: date_date
        description: order date
      - name: revenue
        description: total sales
      - name: quantity
        description: order quantity
      - name: purchase_price
        description: price of all purchases
      - name: purchase_cost
        description: cost of purchases
      - name: margin
        description: cost of goods sold

  - name: finance_days
    description: daily financial report
    columns:                   
      - name: date_date
        description: date of transaction
      - name: nb_transactiond
        description: number of transactions
      - name: revenue
        description: total sales
      - name: average basket
        description: average sale per basket
      - name: average basket bis
        description: average sale per basket bis
      - name: margin
        description: cost of goods sold
      - name: operational margin
        description: operational cost
      - name: purchase_cost
        description: cost of purchases
      - name: shipping_fee
        description: fee per shipping
      - name: logcost
        description: cost of log
      - name: ship_cost
        description: cost of shippig
      - name: quantity
        description: quantity sold
